include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    unawaited_futures: true
    annotate_overrides: true
    avoid_init_to_null: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

analyzer:
  errors:
    todo: ignore
